Added vectors for okta, uptimerobot, pushover and matomo
raivo-otp/issuer-icons pull request #149
Opened 2021-09-12 18:06 UTC by svenkubiak

New vectors for okta, uptimerobot, pushover and matomo.

No fixed width and height and I ran them through. the JSFiddle. How that worked.

2021-09-13 06:33 UTC, svenkubiak commented
Thanks for fixing the viewbox. Regarding the extra input field. Which SVG or information.json is missing?

2021-09-13 17:42 UTC, tijme requested changes

2021-09-14 07:36 UTC, svenkubiak commented on vectors/matomo/matomo.svg
> +<image overflow="visible" xlink:href="data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABQAAD/4QMraHR0cDov
I remove the vector as there seems to be no version without an embeeded image.

2021-09-14 07:37 UTC, svenkubiak commented on vectors/okta/okta.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" style="enable-background:new 0 0 400 134.7;" xml:space="preserve" viewBox
Replaced the infitiy with the original values. Hope that works.

2021-09-14 07:37 UTC, svenkubiak commented on vectors/pushover/pushover.svg
> +<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="-61.77 -61.80 838.78 838.78">
Took the image from the project homepage (https://support.pushover.net/i63-pushover-logos-and-usage). If that doesnt work, we need to remove it as well - couldnt find another version.

2021-09-14 17:59 UTC, merged